sudo: required
 
language: node_js

addons:
  chrome: stable

node_js: 
  - '8'
 
before_install:
  - sudo apt-get update
  - sudo apt-get install -y g++ build-essential
  - export LC_ALL=C
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - selenium-standalone start &
 
cache:
  directories:
    - node_modules
    - .meteor
 
before_script:
  - meteor npm install
  - meteor npm install --unsafe wdio-mocha-framework webdriverio assert
  - meteor &
  - sleep 300 # wait for Meteor to start, it takes some time, 5 minutes should be sufficient
 
script:
  - ./node_modules/.bin/wdio wdio.conf.js # client side tests with wdio
  - meteor test --driver-package=meteortesting:mocha --once --port 5000 # unit tests